### ISSUE TITLE
The rule 'OCLint:compiler warning' does not exist.

### ISSUE THREAD

**Issue by Hellengo** [ChenTF/iOS-sonarShell#1]
使用了提供的插件，扫描报错

log：
1:59:49.754 WARN: Metric 'lines' is an internal metric computed by SonarQube. Provided value is ignored.
11:59:49.890 INFO: Sensor Objective-C Squid Sensor [objectivec] (done) | time=2322ms
11:59:49.890 INFO: Sensor Objective-C OCLint Sensor [objectivec]
11:59:49.891 INFO: parsing /Users/Jenkins/workspace/Sonar-project-alfar-iOS/oclint.xml
11:59:50.468 DEBUG: Collecting issues for /Users/Jenkins/workspace/Sonar-project-alfar-iOS/Alfar/Megvii/Extension/NSArray+ALFExtension.h
11:59:50.468 DEBUG: File /Users/Jenkins/workspace/Sonar-project-alfar-iOS/Alfar/Megvii/Extension/NSArray+ALFExtension.h was found in the project.
11:59:50.494 INFO: ------------------------------------------------------------------------
11:59:50.494 INFO: EXECUTION FAILURE
11:59:50.494 INFO: ------------------------------------------------------------------------
11:59:50.495 INFO: Total time: 6.963s
11:59:50.570 INFO: Final Memory: 46M/331M
11:59:50.570 INFO: ------------------------------------------------------------------------
11:59:50.570 ERROR: Error during SonarQube Scanner execution
The rule 'OCLint:compiler warning' does not exist.
11:59:50.571 DEBUG: Execution getVersion
11:59:50.572 DEBUG: Execution stop
Build step 'Execute shell' marked build as failure

同时下载了https://github.com/mjdetullio/sonar-objective-c 的源码，编译报错，少两个文件

**Comment by ChenTF** [comment]
添加OCLint 0.13版jar包 , 使用新包即可.
